sudo: false
language: node_js
node_js:
  - '10.16.0'
script:
  - pnpm run build && pnpm run lint && pnpm recursive run test-ci
before_install:
  - npm i -g pnpm@4.1.6
install:
  - pnpm install && pnpm recursive install
cache:
  npm: false
  directories:
    - /home/travis/.pnpm-store
branches:
  only:
    - master
